# Generated by Django 5.2.17 on 2026-09-08 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0008_adminpromotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=150)),
                ('expiration', models.DateTimeField()),
                ('requested_by', models.ForeignKey(help_text='The FACTAdmin who requested this reset, for audit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_password_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
