# Generated by Django 5.2.17 on 2026-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0009_adminpasswordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpromotion',
            name='is_new_account',
            field=models.BooleanField(default=False, help_text='True if promote_admin had to create the target User (no existing account for that email) — the confirm step must then also collect a password, instead of just granting the group.'),
        ),
    ]
