"""
Django settings for fact_registration_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import sys
import dj_database_url
from django.core.management.utils import get_random_secret_key
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fact_admin",
    "one_time_verification",
    "registration",
    "corsheaders",
    "shibboleth_auth",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fact_registration_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fact_registration_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DEVELOPMENT_MODE = env.bool("DEVELOPMENT_MODE", False)

if DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
elif len(sys.argv) > 0 and sys.argv[1] != "collectstatic":
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# allow external origins (TODO Modify for production)
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://psauiuc.org",
    "https://fact.psauiuc.org"
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://psauiuc.org",
    "https://fact.psauiuc.org"
]
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CORS_ALLOW_CREDENTIALS = True

# email settings
if "test" in sys.argv:
    print("using file email backend")
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, "test_emails")
else:
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = "587"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = True

# ---------------------------------------------------------------------------
# Shibboleth / SAML SSO Configuration
# ---------------------------------------------------------------------------

# Mock mode: bypasses real UIUC IDP for local development
SAML_MOCK_MODE = env.bool("SAML_MOCK_MODE", default=DEVELOPMENT_MODE)

# SP (Service Provider) settings
SAML_SP_BASE_URL = env("SHIBBOLETH_BASE_URL", default="http://localhost:8000")
SAML_SP_ENTITY_ID = env(
    "SAML_SP_ENTITY_ID",
    default=f"{SAML_SP_BASE_URL}/shibboleth",
)

# Paths to self-signed SP certificates (for signing/encrypting SAML requests)
SAML_SP_CERT_FILE = env(
    "SAML_SP_CERT_FILE",
    default=os.path.join(BASE_DIR, "saml", "sp-cert.pem"),
)
SAML_SP_KEY_FILE = env(
    "SAML_SP_KEY_FILE",
    default=os.path.join(BASE_DIR, "saml", "sp-key.pem"),
)

# IDP (Identity Provider) settings — UIUC defaults
SAML_IDP_ENTITY_ID = env(
    "SAML_IDP_ENTITY_ID",
    default="urn:mace:incommon:uiuc.edu",
)
SAML_IDP_SSO_URL = env(
    "SAML_IDP_SSO_URL",
    default="https://shibboleth.illinois.edu/idp/profile/SAML2/Redirect/SSO",
)
SAML_IDP_SLO_URL = env(
    "SAML_IDP_SLO_URL",
    default="https://shibboleth.illinois.edu/idp/profile/SAML2/Redirect/SLO",
)
SAML_IDP_CERT = env("SAML_IDP_CERT", default="")

# Frontend redirect after successful Shibboleth login
SAML_FRONTEND_REDIRECT_URL = env(
    "SHIBBOLETH_SUCCESS_REDIRECT_URL",
    default="http://localhost:3000/registration-step-2",
)

# Mock mode user attributes (for local testing)
SAML_MOCK_EPPN = env("SAML_MOCK_EPPN", default="testuser@illinois.edu")
SAML_MOCK_EMAIL = env("SAML_MOCK_EMAIL", default="testuser@illinois.edu")
SAML_MOCK_FIRST_NAME = env("SAML_MOCK_FIRST_NAME", default="Test")
SAML_MOCK_LAST_NAME = env("SAML_MOCK_LAST_NAME", default="Illini")

# ---------------------------------------------------------------------------
# Eventbrite Payment Verification Configuration
# ---------------------------------------------------------------------------

# Mock mode: bypasses the real Eventbrite API for local development,
# mirroring SAML_MOCK_MODE above.
EVENTBRITE_MOCK_MODE = env.bool("EVENTBRITE_MOCK_MODE", default=DEVELOPMENT_MODE)

EVENTBRITE_API_TOKEN = env("EVENTBRITE_API_TOKEN", default="")
EVENTBRITE_EVENT_ID = env("EVENTBRITE_EVENT_ID", default="mock-event-id")

EVENTBRITE_TICKET_CLASS_IDS = {
    "variety_show": env("EVENTBRITE_TICKET_CLASS_VARIETY_SHOW", default="mock-variety-show"),
    "workshop": env("EVENTBRITE_TICKET_CLASS_WORKSHOP", default="mock-workshop"),
    "bundle": env("EVENTBRITE_TICKET_CLASS_BUNDLE", default="mock-bundle"),
}
