# Generated by Django 4.2.15 on 2026-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_accountsetup_token_alter_delegate_other_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='is_uiuc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegate',
            name='shibboleth_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='uiuc_eppn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='uiuc_netid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
