# Generated by Django 4.2.15 on 2026-07-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_add_shibboleth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='eventbrite_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('variety_show', 'Variety Show Only'), ('workshop', 'Workshop Only'), ('bundle', 'Variety Show + Workshop Bundle')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UIUCPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('variety_show', 'Variety Show Only'), ('workshop', 'Workshop Only'), ('bundle', 'Variety Show + Workshop Bundle')], max_length=20)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('eventbrite_discount_id', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.delegate')),
            ],
            options={
                'unique_together': {('delegate', 'ticket_type')},
            },
        ),
    ]
