# Generated by Django 4.2.15 on 2026-08-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_delegate_eventbrite_order_id_delegate_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='uiuc_eppn',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='uiuc_netid',
        ),
        migrations.AddField(
            model_name='delegate',
            name='uiuc_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='uiuc_targeted_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
