# Generated by Django 5.2.17 on 2026-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_remove_delegate_uiuc_eppn_remove_delegate_uiuc_netid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiucpromocode',
            name='redeemed_order_id',
            field=models.CharField(blank=True, help_text="The Eventbrite order that redeemed this code, set alongside redeemed_at — an explicit audit trail so 'which order used this code' doesn't have to be inferred via the delegate FK.", max_length=100, null=True),
        ),
    ]
