# Generated by Django 5.2.17 on 2026-09-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_uiucpromocode_redeemed_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='uiuc_netid_self_reported',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
