# Generated by Django 5.2.17 on 2026-09-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_delegate_uiuc_netid_self_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='photo_blur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='photo_opaque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacilitatorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('login_sent_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('facilitator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='registration.facilitator')),
            ],
        ),
    ]
